repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        exclude: >
          (?x)^(
              .git|
              __pycache__|
              docs/conf.py|
              build|
              dist
          )$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path, .isort.cfg]
        name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext, md]
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
