name: Itemset Mining Library CICD

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install codecov tox tox-gh-actions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with tox
        run: tox
      - name: Submit codecov
        run: codecov
  build-publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building with Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to PyPI
        # # if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/master' }}
        ## if: steps.build.outcome == 'success' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
